version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/work:/var/www
    volumes_from:
      - app
  app:
    build: ./docker/php
    container_name: app
    volumes:
      - ./docker/work:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    ports: ["3306:3306"]
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
  node:
    image: node:16-alpine
    container_name: node
    tty: true
    volumes:
      - ./docker/work:/var/www
    working_dir: /var/www
